package-lock.json
package.json
src/App.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/HomePageLanding.tsx
src/components/QuestionAnswers.tsx
src/components/QuestionSection.tsx
src/index.css
src/pages/userprofile.tsx
src/types/question.ts
tsconfig.json

Added MMA Section 

---

src/pages/CreateSession.tsx

feat: Modified Create Session Design

feat: Modified Create Session Design

---

backend/app/main.py
backend/app/routes/session.py
backend/app/schemas/session.py
src/App.tsx
src/pages/CreateSession.tsx
src/pages/EditSession.tsx

Implemented API & Functionalities for Session Create, Edit and delete

Implemented API & Functionalities for Session Create, Edit and delete

---

src/App.tsx
src/components/Header.tsx
src/components/HomePageLanding.tsx
src/pages/AllMentors.tsx
src/pages/Dashboard.tsx
src/pages/MenteeDashboard.tsx

Feat : role based dashboard

---

src/pages/EditSession.tsx
src/pages/MentorDashboard.tsx

UI changed and edit button functionality in mentor dashboard cards

UI Fix and edit button functionality in mentor dashboard cards

---

backend/app/main.py
backend/app/routes/mentor.py
backend/app/schemas/mentor.py
src/App.tsx
src/components/HomePageLanding.tsx
src/pages/AllMentors.tsx
src/pages/CreateSession.tsx
src/pages/EditSession.tsx
src/pages/userprofile.tsx

Dynamic display of profiles 

---

backend/app/routes/mentor.py
src/App.tsx
src/components/Header.tsx
src/pages/editprofile.tsx
src/pages/userprofile.tsx

Edit Profile Added for Mentors

Edit Profile Added for Mentors

---

src/pages/editprofile.tsx
src/pages/userprofile.tsx

Edit extra fields added

---

src/App.tsx
src/components/BookingDetails.tsx
src/components/HomePageLanding.tsx

Booking Details Functionality Added

Booking Details Functionality Added

---

backend/app/routes/session.py
src/components/HomePageLanding.tsx

Group session Dynamic Added

---

src/components/HomePageLanding.tsx

Group session UI Fix

---

src/components/HomePageLanding.tsx
src/pages/AllMentors.tsx

All mentors page Completed

---

backend/app/main.py

fix: Add missing CORS origin for production environment

fix: Add missing CORS origin for production environment

---

frontend/src/pages/MenteeDashboard.tsx

fix: Update API_URL import to use centralized configuration

fix: Update API_URL import to use centralized configuration

---

frontend/src/pages/AllMentors.tsx

Group sesions Fix

---

backend/app/database.py
backend/app/main.py
backend/app/routes/upload.py
backend/requirements.txt
docker-compose.yml
frontend/Dockerfile.development
frontend/src/components/HomePageLanding.tsx
frontend/src/components/MentorProfileForm.tsx
frontend/src/components/QuestionSection.tsx
frontend/src/index.css
frontend/src/pages/AMASessionform.tsx
frontend/src/pages/AllMentors.tsx
frontend/src/pages/CreateSession.tsx
frontend/src/pages/userprofile.tsx
frontend/vite.config.ts

Added the docs changes

---

.gitignore
backend/app/utils/google_calendar.py
frontend/src/components/HomePageLanding.tsx
frontend/src/index.css

card scroll fix in landing page for 1on1 section and upcoming section

Fix page UI and document changes

---

backend/app/main.py
backend/app/routes/upload.py
frontend/src/components/MentorProfileForm.tsx

fix: Update upload route and API call for profile photo upload

fix: Update upload route and API call for profile photo upload

---

backend/app/routes/upload.py

fix: Update endpoint path for profile photo upload

fix: Update endpoint path for profile photo upload

---

backend/app/routes/upload.py

fix: Correct endpoint path for profile photo upload

fix: Correct endpoint path for profile photo upload

---

frontend/src/pages/userprofile.tsx

feat: Add profile creation state and loading indicators

feat: Add profile creation state and loading indicators

---

backend/app/routes/upload.py

feat: Add profile creation state and loading indicators

feat: Add profile creation state and loading indicators 
